### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ratijas** [SublimeText/QML#8]
Hi Sergey,

I'm an active KDE developer, and a heavy user of Sublime Text. As such, I'd like to request that you grant me maintainer permissions for this project — QML integration for Sublime Text & Merge.

My goals are, first and foremost, fix and update syntax definitions to support modern QML features, and also possibly integrate it with LSP created by other developer of our community.

Worst case scenario: I'll have to fork it and re-publish as a new package. Best case scenario: we could transfer this repo under [Sublime Text Packages](https://github.com/SublimeText) GitHub organization.

**Comment by skozlovf** [comment]
Hello, @ratijas.
I'm ok with your request. I haven't been using Qt/QML for quite a while . If still useful for the community and you're interested to continue development I don't mind. Maybe I join you later if back to Qt/QML ;)

So you want to me to transfer ownership to you or collaborator access is ok to you?

**Comment by ratijas** [comment]
Hi, thanks for collaborator permissions, that would be a good start. I haven't actually contacted Community Packages project yet, but we'll see.

I started from rewriting syntax definitions in a modern *.sublime-syntax YAML format. I kept old copies of XML around, but so far it seems like it's gonna be a complete rewrite from scratch rather than upgrade of existing code base. I left most of the snippets intact, just cleaned up a bit some of them. I also set up CI tests, which is simply a copy-paste of GitHub Actions workflow definition from one of the official projects.

Branching turned out be quite useful, and an ability to include scopes from other files really shines bright. Imports and component declarations are done, and I hope I could finish with basic properties syntax by the end of this week.

**Comment by skozlovf** [comment]
Sounds awesome!
Feel free to contact me.

**Comment by ratijas** [comment]
I've talked with maintainers on Sublime Text Packages Discord server.  They are OK with taking the plugin under umbrella, but it should be done publicly on GitHub issues. So I think I'll reuse this issue (because I can't find the right spot to open a new one in their GitHub organization).

@FichteFoll

**Comment by FichteFoll** [comment]
Hello @skozlovf, I have sent you an invite to the SublimeText org. After you accepted it, you are able to transfer the repository to the org in your repository's settings. I will set up the necessary permissions afterwards (adding you and @ratijas as a collaborator) and someone (preferrably @ratijas) will need to update the package entry at the package control channel.

**Comment by skozlovf** [comment]
@ratijas I've accepted @FichteFoll invitation.

**Comment by ratijas** [comment]
I think the transfer part was also implied to be done by you, @skozlovf. I don't have permissions for that anyway :)

**Comment by skozlovf** [comment]
@ratijas Ok, give me some time.

**Comment by FichteFoll** [comment]
Yes, exactly, only you can do that.

I'll be on vacation from Saturday on, so feel free to ping @keith-hall after the move.

**Comment by skozlovf** [comment]
@ratijas @FichteFoll I've moved the repo to the SublimeText org.
@ratijas Could you update the package entry?
@keith-hall Could you check and perform other necessary steps?

Thanks!

**Comment by keith-hall** [comment]
@skozlovf I have made you an admin of this repo.
@ratijas confirmed you have write access and can manage issues/PRs

**Comment by ratijas** [comment]
Thank you everyone! I'll do the rest during next few days. As you can see by activity in #10, I'm still amending my own branch as I work on KDE stuff and keep finding more and more corner-cases and lesser-known quirks of QML. So, I want to polish it a bit more before publishing.

**Comment by FichteFoll** [comment]
I went ahead with renaming the repo to just "QML" since it's already namespaced by the organization now.

**Comment by ratijas** [comment]
Cool. And I'll finally handle the merging & publishing this week.

**Comment by ratijas** [comment]
https://github.com/wbond/package_control_channel/pull/8577

**Comment by ratijas** [comment]
Package Control channel has been updated :tada: 
The last things to do before tagging 1.0 are: write an [upgrade message](https://packagecontrol.io/docs/messaging), add an icon, and update README

**Comment by ratijas** [comment]
Took me a while, but I finally found some time & motivation to push it over the line.

I'd be honest, writing texts like readme and messages is not my strongest skill — even short paragraphs are such a drainer for me. Hope you'll like the new icon 🙃
